# Generated by Django 4.0.6 on 2022-07-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0003_blog_category_product_subscribe_myuser_is_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='arrivals_url',
        ),
    ]
