# Generated by Django 4.0.6 on 2022-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0004_remove_arrival_arrivals_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrival',
            old_name='arrivals_title',
            new_name='arrivals_text',
        ),
        migrations.AddField(
            model_name='arrival',
            name='arrivals_size',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
