# Generated by Django 4.0.6 on 2022-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0005_rename_arrivals_title_arrival_arrivals_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='arrivals_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
